### ISSUE TITLE
Builder option for setting icon color

### ISSUE THREAD

**Issue by lpellegr** [sjwall/MaterialTapTargetPrompt#12]
It seems that if an icon is set manually with `setIcon`, then the default color for this icon is blue and I cannot figure out how to change the color for this image. Is it a missing option?

**Comment by sjwall** [comment]
It is tinting the icon colour the back colour when `setIcon` is called, which it should not be doing.

I will change it so that it is an explicit option to set the icon tint which by default will be the background colour with the option to disable tinting. I will fix this today but as temporary fix calling `setBackgroundColour` or `setBackgroundColourFromRes` before calling `setIcon` should fix it.

**Comment by sjwall** [comment]
It will carry on as before using the default blue colour to tint the icon.
There are 4 new methods in release v1.4.0 which allow the tint to be customised or removed:

1. `setIconDrawableColourFilter(int colour)`
2. `setIconDrawableColourFilterFromRes(colour resource id)`
3. `setIconDrawableTintList(ColorStateList)`
4. `setIconDrawableTintMode(PorterDuff.Mode)`

The easiest way for you to change the tint colour is using the first method.
If you want to remove the tint call either the 3<sup>rd</sup> or 4<sup>th</sup> method with `null` as the parameter.

**Comment by lpellegr** [comment]
Great, thank you a lot!
