### ISSUE TITLE
Unable to add prompt to spinner dropdown

### ISSUE THREAD

**Issue by ccrockatt** [sjwall/MaterialTapTargetPrompt#133]
A spinner dropdown shows up as a popup in the layout inspector, here is a screenshot:

![spinnerdropdown](https://user-images.githubusercontent.com/9635982/45102935-c3525480-b0fc-11e8-9a95-c36361db0e81.png)

I have tried to show the prompt when the spinner item is selected but that is too late as the popup has already disappeared.

![onlistitemclickedandspinneronitemselectedcombo](https://user-images.githubusercontent.com/9635982/45103407-d74a8600-b0fd-11e8-817f-5ddc205987db.png)

```
eventSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {

	public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
			showEventProgressInfoForWizard(view);
```

*********************************************************

I have also tried adding the prompt in to the getView function of the spinner's adapter as follows:

```
	@Override
	public View getDropDownView(int position, View convertView, ViewGroup parent) {
		View ddView = super.getDropDownView(position, convertView, parent);
		new MaterialTapTargetPrompt.Builder(owningActivity)
				.setPrimaryText("See the progress bar blah blah blah.")
				.setAnimationInterpolator(new FastOutSlowInInterpolator())
				.setPromptBackground(new RectanglePromptBackground())
				.setPromptFocal(new RectanglePromptFocal())
				.setTarget(ddView)
				.show();

		return ddView;
	}
```

but that results in a muddled prompt and screen including the dropdown somehow being duplicated on the main activity (the "Xyz" list item is not supposed to be on the underlying screen, just in the dropdown):

![spinnerdropdownpromptmuddled](https://user-images.githubusercontent.com/9635982/45102577-09f37f00-b0fc-11e8-924a-9e1eda1160a9.png)

When I debug to try to find the correct parent to sent to the MaterialTapTargetPrompt.Builder I see that the view is a relative layout and the mParent value is null while the ViewGroup parent is the spinner:
![variableswhiledebugginggetdropdownview](https://user-images.githubusercontent.com/9635982/45101490-97819f80-b0f9-11e8-974a-d2a73b416d71.JPG)

Thanks for any help or insight

**Comment by sjwall** [comment]
Thanks for submitting a detailed report, I have spent quite a bit of time this afternoon trying to get this to work and haven't managed to find a solution yet :(

__How the library works__
When the builder is created with the supplied Activity/Fragment a [ResourceFinder](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/ResourceFinder.java) is created. For Activity this is [ActivityResourceFinder](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/ActivityResourceFinder.java)
The resource finder is used to get the correct view parent to put the prompt in and get any resources. For activities it [gets the window decor view](https://github.com/sjwall/MaterialTapTargetPrompt/blob/94aa5a01954db9ca4dcf78603d4a922c4a61e44b/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/ActivityResourceFinder.java#L58) and adds the prompt view to it.
The prompt then draws the target view on top

__The problem__
Looking a the Spinner source code it uses an AlertDialog to show the drop down. This AlertDialog is shown on top the decor view. Using [this example](https://stackoverflow.com/a/25137740/8345775) I was only able to hook into an event before the AlertDialog was shown, this means the prompt would always be behind the AlertDialog even when showing the prompt view in a PopupWindow.
It did allow adding the prompt to the drop down view hierarchy by exposing the drop down view parent but it would clip the prompt to the drop down bounds and the prompt was still displayed behind the view items

__Potential solution__
Some how execute the show prompt after the drop down has shown, then change the prompt to display in a PopupWindow so that it is above the drop down. I have pushed the code that I have written so far to the [spinner branch](https://github.com/sjwall/MaterialTapTargetPrompt/tree/spinner)

Hopefully this is of some help
I will have another a look at this later next week, please let me know if you find anything

**Comment by ccrockatt** [comment]
Great, thanks so much, I'll work through what you've sent soon to see if I can build on it.

Cheers!

**Comment by sjwall** [comment]
Same issue as #62
