### ISSUE TITLE
java.lang.NullPointerException:    at android.graphics.Typeface.create (Typeface.java:849)

### ISSUE THREAD

**Issue by AlexeyGodyaev** [sjwall/MaterialTapTargetPrompt#188]
Redmi Note 9.  Android 10 (SDK 29)
java.lang.NullPointerException: 
  at android.graphics.Typeface.create (Typeface.java:849)
  at uk.co.samuelwall.materialtaptargetprompt.extras.PromptUtils.setTypefaceFromAttrs (PromptUtils.java:127)
  at uk.co.samuelwall.materialtaptargetprompt.extras.PromptOptions.load (PromptOptions.java:240)
  at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder.<init> (MaterialTapTargetPrompt.java:959)
  at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder.<init> (MaterialTapTargetPrompt.java:942)

**Comment by sjwall** [comment]
Looks like this occurs because the font being used is not available on the device being used

**Comment by akwizgran** [comment]
@sjwall thanks for creating this excellent library!

We're seeing crashes from this issue in our app. We don't set a custom typeface for the tap target. Do you have any suggestions for how to work around the issue? For example, is there a way to discover the device's default typeface and use that as a fallback?

**Comment by akwizgran** [comment]
I think it might be possible to trigger this issue if `R.styleable.PromptView_mttp_primaryTextTypeface` is unset.

In that case `a.getInt(R.styleable.PromptView_mttp_primaryTextTypeface, 0)` will default to `0` [here](https://github.com/sjwall/MaterialTapTargetPrompt/blob/7ce5329ff18e5bccc563f71aff0e0eee40c42d23/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/PromptOptions.java#L253), which will cause the switch statement [here](https://github.com/sjwall/MaterialTapTargetPrompt/blob/099d7519c33be4b6d0dad2179b61fc1c6b97d602/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/PromptUtils.java#L113) to fall through without setting `tf`, which will cause the observed NPE in `Typeface.create()`.

If the default for `a.getInt(R.styleable.PromptView_mttp_primaryTextTypeface, 0)` was changed to `1`, or if the switch statement was updated to treat `0` the same as `1`, then the sans serif typeface would be returned in this case instead of crashing.

**Comment by akwizgran** [comment]
The switch statement is only reached if `Typeface.create()` fails to create the typeface named by `R.styleable.PromptView_mttp_primaryTextFontFamily`, which would explain why we're only seeing this issue on certain devices (Xiaomi devices in India, which presumably have different fonts installed than our test devices).

**Comment by sjwall** [comment]
Thank you for the detail! I have added a default case based on your investigation. It will be in the next release

**Comment by akwizgran** [comment]
Fantastic, thank you!
