### ISSUE TITLE
Can i reduce the background radius to half its size

### ISSUE THREAD

**Issue by chinmoyeedash** [sjwall/MaterialTapTargetPrompt#23]
I do not want the blue background to almost fill the activity. Can its size be minimized to lets say half??

**Comment by sjwall** [comment]
The background radius is calculated based on the keylines in the design guidelines (see diagram below). The background radius originates from the target point, I plan on implementing functionality to change this so that it can be styled like the first example in the guidelines [here](https://material.google.com/growth-communications/feature-discovery.html#feature-discovery-design-patterns), this would then allow for the background radius to be reduced.

![Keylines](https://material-design.storage.googleapis.com/publish/material_v_9/0B4kv-3uZbS1qdUNnYWpaeldIcDQ/useredu_er_feasturedisc_design_phone_centered.png)

The keylines can be customised using the following functions:

- `setMaxTextWidth` Defines the maximum width that the text can be. If the screen width is less, then that is used instead.  The default is 400dp. By reducing this, the background radius will be reduced.
- `setTextPadding` This is the 40dp shown either side of the text in the diagram above
- `setFocalToTextPadding` This is the 20dp shown in the diagram above. Reducing this will reduce the distance that the text is from the centre.

**Comment by chinmoyeedash** [comment]
Thanks, changing the setMaxTextWidth helped.
