### ISSUE TITLE
problem with long touch

### ISSUE THREAD

**Issue by MahdiTaghipour** [sjwall/MaterialTapTargetPrompt#40]
Hi, thank you for your great library.
there is a problem with long touch. i have implemented a step by step procedure and inside "onHidePromptComplete" of a prompt I fire the next prompt. when I long touch a prompt, i see 2 prompts showing simultaneously and every thing unsettles. i have attached some lines of my code.
thanks in advance.
[sample4.txt](https://github.com/sjwall/MaterialTapTargetPrompt/files/752157/sample4.txt)

**Comment by sjwall** [comment]
I have been unable to replicate the long touch showing multiple prompts. 

The only thing I could suggest to do, is for you to add break points where each prompt is created so that the call hierarchy can be check to see where the call to show the prompt. From this you should be able to see if the show prompt is triggered twice from `onHidePromptComplete`. 
If it isn't calling it twice from their it could be the if statements at the start where you check if the prompt has been shown before, creating an infinite loop.

Hope that helps

**Comment by MahdiTaghipour** [comment]
The problem was that showing prompt was triggered twice from onHidePromptComplete when we long touch the prompt. I solved this problem by using flags to handle the issue.
thank you.

**Comment by sjwall** [comment]
I finally managed to get the `onHidePromptComplete` event happening twice. Some times the animation listener was calling `onAnimationEnd` twice. This is fixed in v1.9.

**Comment by MahdiTaghipour** [comment]
thank you so much.
