### ISSUE TITLE
Unable set the dismiss actoin only on the focal view

### ISSUE THREAD

**Issue by mzyadatuba** [sjwall/MaterialTapTargetPrompt#5]
Couldn't control the touch listener on the rest of the view, only on the focal

**Comment by sjwall** [comment]
The _onHidePrompt_ method in the _OnHidePromptListener_ is called when ever the view is touched.
The parameter _tappedTarget_ is _true_ when the focal/target is pressed and false otherwise.

If the touched location is the focal/target, by default, the prompt lets the touch event pass through the view and to the underlying target view. To stop the touch event passing through, call _setCaptureTouchEventOnFocal(true)_ on the builder instance.

Hope this solves the issue you are having

**Comment by mzyadatuba** [comment]
thank you for your replay, but actually you got me wrong, what i need is to make the view dismiss only if the user clicked on the focal/target view, otherwise, i need the tutorial to remains. currently, the tutorial will disappear if the user clicked outside the focal/target, this is my issue.

**Comment by sjwall** [comment]
I shall have a look at adding an option to stop the prompt automatically dismissing when the user touches it

**Comment by mzyadatuba** [comment]
that will be great

**Comment by sjwall** [comment]
Commits 0c94c7fe0efe47494fd75104415139feb0c67059 and 7ac2c11a38a06e300ccce2995ade84e74f12672e add methods to stop the prompt automatically dismissing when the user touches it.

These methods are in the builder class:

- setAutoDismiss (default is true)
- setAutoFinish (default is true)
- setCaptureTouchEventOutsidePrompt (default is false and allows touch events outside the prompt)

The default functionality remains the same and an example has been added to the sample app.

**Comment by mzyadatuba** [comment]
Grate thank you
