### ISSUE TITLE
Adding some "don't show me again" checkbox or button

### ISSUE THREAD

**Issue by par4301** [sjwall/MaterialTapTargetPrompt#55]
I wonder if it would be possible to add some kind of check box or button, so I can add this "don't show me again" property to that.

Thanks

**Comment by sjwall** [comment]
Currently the Material Design Onboarding guidelines do not give any guidance on how such functionality could be implemented. Without guidelines it is very open to personal preference on how to implement said functionality. 
Instead of adding `don't show me again` I would suggest detecting if the user has used the functionality that the prompt is prompting the user to use, if they have then don't show the prompt. See the [Volume & frequency guidelines](https://material.io/guidelines/growth-communications/feature-discovery.html#feature-discovery-volume-frequency).
