### ISSUE TITLE
Not working for menu items

### ISSUE THREAD

**Issue by tevevizor** [sjwall/MaterialTapTargetPrompt#57]
When menu item ID is set as target, circle is not shown around it, nothing happens.

**Comment by sjwall** [comment]
It is most likely that the menu view can't be found. If `null` is returned by `builder.create()` or `builder.show()` it means that the target view can not be found.

Check that the view can be found using `activity.findViewById(int)`.

You can also target the menu item view explicitly if you can find it, using `builder.setTarget(View)`

Hope this helps, if you are still having problems please reopen and provide more information, such how the menus are being created and Android version so that I can investigate.
