### ISSUE TITLE
Tap Target + PopupWindow

### ISSUE THREAD

**Issue by NiranjanShah** [sjwall/MaterialTapTargetPrompt#62]
Tap Target does not work on PopupWindow.
it is not able to find the target

**Comment by sjwall** [comment]
Due to the way that the library works it is currently not compatible with PopupWindow.
To get the prompt to work with PopupWindow it needs to be one its self so that it renders above it. I am looking at the possibility of changing the library so that the prompt extends PopupWindow and is then displayed above the targeted PopupWindow (4e7dcc772c77db3e6cb9a8d8746f4de58639602b).

**Comment by bagintz** [comment]
@sjwall Would that also fix it with a DialogFragment?

**Comment by bagintz** [comment]
android.support.v4.app.DialogFragment to be specific
