### ISSUE TITLE
Doesn't work with BottomSheetDialogFragment

### ISSUE THREAD

**Issue by hfahmy** [sjwall/MaterialTapTargetPrompt#63]
Doesn't work with [BottomSheetDialogFragment](https://developer.android.com/reference/android/support/design/widget/BottomSheetDialogFragment.html). 

The ShowCaseView gets drawn behind the bottom sheet. Any quick workarounds?

**Comment by sjwall** [comment]
This is fixed in #24 and will be released in v2.0.0

**Comment by sjwall** [comment]
This fix has been released in v1.11.0 along with an [example](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/BottomSheetDialogFragmentExample.java)

Instead of supplying an activity to the builder supply the dialog instead.

```java
new MaterialTapTargetPrompt.Builder(getDialog())
```
