### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by soad130** [sjwall/MaterialTapTargetPrompt#7]
Hello. I havent used this library in my project yet , but i did try the demonstration app. This looks awesome. There is one small problem tho . There is a noticable delay before animation starts , is there any way to fix this ?

**Comment by sjwall** [comment]
Thanks for feed back and noticing the delay!

The delay before displaying the prompt was due to a start delay being incorrectly added to the animation used to display the prompt.

The delay before the idle animation starts is intentional, in the examples in the [guidelines][1] there is a delay before the idle animation starts.

[1]: https://www.google.com/design/spec/growth-communications/feature-discovery.html#feature-discovery-design
