### ISSUE TITLE
Listen for Drop instead of Pressed

### ISSUE THREAD

**Issue by FridayShamblen** [sjwall/MaterialTapTargetPrompt#74]
Hi there,

Thank you for this lovely library!

I would like to listen for a drop event instead of a press event---is this possible and if so, what would I do?  Here's a snippet of what I'm using in the Builder:
```
.setPromptStateChangeListener(new MaterialTapTargetPrompt.PromptStateChangeListener() {
                    @Override
                    public void onPromptStateChanged(MaterialTapTargetPrompt prompt, int state) {
                    }
                })
```

**Comment by sjwall** [comment]
The PromptStateChangeListener doesn't report drop events. Would providing access to the view [setOnDragListener](https://developer.android.com/reference/android/view/View.html#setOnDragListener(android.view.View.OnDragListener)) method so that a [View.OnDragListener](https://developer.android.com/reference/android/view/View.OnDragListener.html) could be set solve this for you?

**Comment by sjwall** [comment]
PR welcome but have no intention to implement this
